### ISSUE TITLE
Compiling on Ubuntu errors

### ISSUE THREAD

**Issue by kito2** [ranisalt/forgottenserver#6]
Using this guide: https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu

This is the error: 
![image](https://user-images.githubusercontent.com/21250744/41197235-9083fe5e-6c24-11e8-86fe-31a659794547.png)

**Comment by ranisalt** [comment]
You are missing `boost-filesystem-dev` package

**Comment by kito2** [comment]
![image](https://user-images.githubusercontent.com/21250744/41208036-6f67dbfa-6cec-11e8-9aaf-9c1deea4c6e1.png)

Unable to install...
